site:
    title: 猫叔の杂记 · 手帐
    subtitle: 代码，美术，音乐与二次元
    logo: -/images/avatar.jpg
    limit: 10
    theme: theme
    disqus: imeoer
    # root: /blog

authors:
    me:
        name: 猫叔
        intro: 程序员，关注设计与二次元
        avatar: -/images/avatar.jpg

build:
    port: 8888
    copy:
        # 构建时将会复制以下目录/文件到 public 目录
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    publish: |
        # 执行 ink publish 命令将会执行以下脚本
        git add . -A
        git commit -m "update"
        git push origin
